#!/usr/bin/env python3
"""
Regenerate ``app.models.untp.v0_7_0`` Pydantic models from bundled UNTP JSON Schema.

``datamodel-code-generator`` cannot parse ``prefixItems`` on ``@context`` in the upstream
schemas; this script strips ``prefixItems`` recursively in a temp copy, runs codegen,
then renames the root ``Model`` class in each output file.

Usage (from ``backend/``)::

    uv run --with datamodel-code-generator python scripts/generate_untp_pydantic_models.py
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
BUNDLED_SCHEMAS = BACKEND_ROOT / "untp/bundled/v0.7.0/schemas"
OUT = BACKEND_ROOT / "app/models/untp/v0_7_0"

HEADER = (
    "# generated by datamodel-codegen from UNTP v0.7.0 {filename}\n"
    "# (bundled copy under untp/bundled/; JSON `prefixItems` stripped for codegen — "
    "see scripts/generate_untp_pydantic_models.py)\n"
)

JOBS: list[tuple[Path, Path, str, str]] = [
    (
        Path("ConformityCredential.json"),
        OUT / "dcc/digital_conformity_credential.py",
        "ConformityCredential.json",
        "DigitalConformityCredential",
    ),
    (
        Path("ConformityAttestation.json"),
        OUT / "dcc/conformity_attestation.py",
        "ConformityAttestation.json",
        "ConformityAttestation",
    ),
    (
        Path("dia/DigitalIdentityAnchor.json"),
        OUT / "dia/digital_identity_anchor.py",
        "DigitalIdentityAnchor.json",
        "DigitalIdentityAnchor",
    ),
    (
        Path("dia/RegisteredIdentity.json"),
        OUT / "dia/registered_identity.py",
        "RegisteredIdentity.json",
        "RegisteredIdentity",
    ),
]


def strip_prefix_items(obj: object) -> None:
    if isinstance(obj, dict):
        obj.pop("prefixItems", None)
        for v in obj.values():
            strip_prefix_items(v)
    elif isinstance(obj, list):
        for item in obj:
            strip_prefix_items(item)


def rename_root_model(text: str, root_name: str) -> str:
    needle = 'class Model(BaseModel):\n    """'
    if needle not in text:
        raise SystemExit(
            "expected root class Model(BaseModel) with docstring marker in output"
        )
    return text.replace(
        needle, f'class {root_name}(BaseModel):\n    """', 1
    )


def replace_header(text: str, filename: str) -> str:
    lines = text.splitlines(keepends=True)
    i = 0
    while i < len(lines) and (
        lines[i].startswith("# generated by datamodel-codegen")
        or lines[i].startswith("#   filename:")
        or lines[i].startswith("#   timestamp:")
    ):
        i += 1
    if i < len(lines) and lines[i].strip() == "":
        i += 1
    rest = "".join(lines[i:])
    return HEADER.format(filename=filename) + "\n" + rest


def fix_codegen_empty_type_wrappers(path: Path) -> None:
    """
    datamodel-codegen emits empty ``Type`` / ``Type3`` BaseModels and unions them with
    ``list[str]`` for JSON Schema ``type`` arrays; real JSON uses plain lists, which
    then fail validation. Replace with ``list[str]`` defaults only.
    """
    if path.name == "digital_conformity_credential.py":
        text = path.read_text(encoding="utf-8")
        text = re.sub(
            r"\nclass Type\(BaseModel\):\n    model_config = ConfigDict\(\n        populate_by_name=True,\n    \)\n\n",
            "\n",
            text,
            count=1,
        )
        text = re.sub(
            r"\nclass Type3\(BaseModel\):\n    model_config = ConfigDict\(\n        populate_by_name=True,\n    \)\n\n",
            "\n",
            text,
            count=1,
        )
        text = text.replace(
            "type: list[str] | Type | None = Field(\n        default_factory=lambda: Type.model_validate([\"CredentialIssuer\"])\n    )",
            'type: list[str] | None = Field(\n        default_factory=lambda: ["CredentialIssuer"]\n    )',
        )
        text = text.replace(
            "type: list[str] | Type | None = Field(\n        default_factory=lambda: Type.model_validate(\n            [\"DigitalConformityCredential\", \"VerifiableCredential\"]\n        )\n    )",
            'type: list[str] | None = Field(\n        default_factory=lambda: [\n            "DigitalConformityCredential",\n            "VerifiableCredential",\n        ]\n    )',
        )
        text = re.sub(
            r"type: list\[str\] \| Type3 \| None = Field\(\s*\n\s*default_factory=lambda: Type3\.model_validate\(\[\"([^\"]+)\"\]\)\s*\n\s*\)",
            r'type: list[str] | None = Field(\n        default_factory=lambda: ["\1"]\n    )',
            text,
        )
        path.write_text(text, encoding="utf-8")
    elif path.name == "conformity_attestation.py":
        text = path.read_text(encoding="utf-8")
        text = re.sub(
            r"\nclass Type\(BaseModel\):\n    model_config = ConfigDict\(\n        populate_by_name=True,\n    \)\n\n",
            "\n",
            text,
            count=1,
        )
        text = re.sub(
            r"type: list\[str\] \| Type \| None = Field\(\s*\n\s*default_factory=lambda: Type\.model_validate\(\[\"([^\"]+)\"\]\)\s*\n\s*\)",
            r'type: list[str] | None = Field(\n        default_factory=lambda: ["\1"]\n    )',
            text,
        )
        path.write_text(text, encoding="utf-8")


def main() -> None:
    if not BUNDLED_SCHEMAS.is_dir():
        sys.exit(f"missing bundled schemas: {BUNDLED_SCHEMAS}")

    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        tmp_root = Path(tmp)
        for path in sorted(BUNDLED_SCHEMAS.rglob("*.json")):
            data = json.loads(path.read_text(encoding="utf-8"))
            strip_prefix_items(data)
            rel = path.relative_to(BUNDLED_SCHEMAS)
            target = tmp_root / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(json.dumps(data, indent=2), encoding="utf-8")

        common = [
            "datamodel-codegen",
            "--input-file-type",
            "jsonschema",
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.12",
            "--use-schema-description",
            "--field-constraints",
            "--use-default",
            "--use-default-kwarg",
            "--allow-population-by-field-name",
            "--use-double-quotes",
        ]

        for rel_src, out_path, src_label, root_name in JOBS:
            src = tmp_root / rel_src
            if not src.is_file():
                sys.exit(f"missing temp schema: {src}")
            out_path.parent.mkdir(parents=True, exist_ok=True)
            cmd = [
                "uv",
                "run",
                "--with",
                "datamodel-code-generator",
                *common,
                "--input",
                str(src),
                "--output",
                str(out_path),
            ]
            subprocess.run(cmd, check=True, cwd=BACKEND_ROOT)

            text = out_path.read_text(encoding="utf-8")
            text = rename_root_model(text, root_name)
            text = replace_header(text, src_label)
            out_path.write_text(text, encoding="utf-8")
            fix_codegen_empty_type_wrappers(out_path)

    print("Wrote:", OUT)


if __name__ == "__main__":
    main()
