#!/usr/bin/env python3
"""
Regenerate UNTP v0.7.0 DCC Pydantic models from bundled JSON Schema.

Why this exists
    Official UNTP artefacts are JSON Schema. We want typed Pydantic models that
    track those schemas without hand-maintaining hundreds of fields.

Why datamodel-codegen (and not “just jsonschema”)
    :mod:`jsonschema` is enough for *validation*; codegen is for *typed parsing*
    and IDE-friendly models. You could drop codegen and validate only—different
    tradeoff.

Pipeline
    1. Copy bundled schemas to a temp tree and strip every ``prefixItems`` key.
       ``datamodel-codegen`` does not handle ``prefixItems`` on ``@context``.
    2. Run codegen once on ``ConformityCredential.json`` only. That schema
       inlines ``$defs.ConformityAttestation``, so one module gets credential +
       attestation (no duplicate enums across files).
    3. Rename the root ``Model`` class and normalize the file header.
    4. **Repair** known bad emit for VC ``type`` arrays (see
       :func:`_repair_codegen_vc_type_fields`). This is **string surgery** tied
       to current codegen output; after upgrading ``datamodel-code-generator``,
       re-run the script and inspect ``git diff``, or adjust the repair steps.

Usage (from ``backend/``)::

    uv run --with datamodel-code-generator python scripts/generate_untp_pydantic_models.py
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
BUNDLED_SCHEMAS = BACKEND_ROOT / "untp/bundled/v0.7.0/schemas"
OUT_DIR = BACKEND_ROOT / "app/models/untp/v0_7_0"
OUT_FILE = OUT_DIR / "dcc.py"

HEADER = (
    "# generated by datamodel-codegen from UNTP v0.7.0 {filename}\n"
    "# (bundled copy under untp/bundled/; JSON `prefixItems` stripped for codegen — "
    "see scripts/generate_untp_pydantic_models.py)\n"
)

# Single root schema → output path, schema label for header, Pydantic root class name.
SCHEMA_JOB = (
    Path("ConformityCredential.json"),
    OUT_FILE,
    "ConformityCredential.json",
    "DigitalConformityCredential",
)

CODEGEN_BASE = (
    "datamodel-codegen",
    "--input-file-type",
    "jsonschema",
    "--output-model-type",
    "pydantic_v2.BaseModel",
    "--target-python-version",
    "3.12",
    "--use-schema-description",
    "--field-constraints",
    "--use-default",
    "--use-default-kwarg",
    "--allow-population-by-field-name",
    "--use-double-quotes",
)


def _strip_prefix_items(obj: object) -> None:
    if isinstance(obj, dict):
        obj.pop("prefixItems", None)
        for v in obj.values():
            _strip_prefix_items(v)
    elif isinstance(obj, list):
        for item in obj:
            _strip_prefix_items(item)


def _materialize_stripped_schemas(dest: Path) -> None:
    for path in sorted(BUNDLED_SCHEMAS.rglob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        _strip_prefix_items(data)
        rel = path.relative_to(BUNDLED_SCHEMAS)
        target = dest / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(data, indent=2), encoding="utf-8")


def _rename_root_model(text: str, root_name: str) -> str:
    needle = 'class Model(BaseModel):\n    """'
    if needle not in text:
        sys.exit("codegen output missing expected root class Model(BaseModel) with docstring")
    return text.replace(needle, f'class {root_name}(BaseModel):\n    """', 1)


def _replace_generated_header(text: str, filename: str) -> str:
    lines = text.splitlines(keepends=True)
    i = 0
    while i < len(lines) and (
        lines[i].startswith("# generated by datamodel-codegen")
        or lines[i].startswith("#   filename:")
        or lines[i].startswith("#   timestamp:")
    ):
        i += 1
    if i < len(lines) and lines[i].strip() == "":
        i += 1
    return HEADER.format(filename=filename) + "\n" + "".join(lines[i:])


def _repair_codegen_vc_type_fields(text: str) -> str:
    """
    Remove empty ``Type`` / ``Type3`` wrapper classes and collapse ``Field``s that
    use ``Type.model_validate([...])`` to plain ``list[str]`` defaults.

    JSON uses ``"type": ["VerifiableCredential", ...]``; codegen sometimes emits
    unusable unions. This is **not** spec logic—only output normalization.
    """
    for pattern in (
        r"\nclass Type\(BaseModel\):\n    model_config = ConfigDict\(\n        populate_by_name=True,\n    \)\n\n",
        r"\nclass Type3\(BaseModel\):\n    model_config = ConfigDict\(\n        populate_by_name=True,\n    \)\n\n",
    ):
        text = re.sub(pattern, "\n", text, count=1)

    text = text.replace(
        "type: list[str] | Type | None = Field(\n        default_factory=lambda: Type.model_validate([\"CredentialIssuer\"])\n    )",
        'type: list[str] | None = Field(\n        default_factory=lambda: ["CredentialIssuer"]\n    )',
    )
    text = text.replace(
        "type: list[str] | Type | None = Field(\n        default_factory=lambda: Type.model_validate(\n            [\"DigitalConformityCredential\", \"VerifiableCredential\"]\n        )\n    )",
        'type: list[str] | None = Field(\n        default_factory=lambda: [\n            "DigitalConformityCredential",\n            "VerifiableCredential",\n        ]\n    )',
    )
    text = re.sub(
        r"type: list\[str\] \| Type3 \| None = Field\(\s*\n\s*default_factory=lambda: Type3\.model_validate\(\[\"([^\"]+)\"\]\)\s*\n\s*\)",
        r'type: list[str] | None = Field(\n        default_factory=lambda: ["\1"]\n    )',
        text,
    )
    return text


def _run_codegen(schema_path: Path, out_path: Path) -> None:
    cmd = [
        "uv",
        "run",
        "--with",
        "datamodel-code-generator",
        *CODEGEN_BASE,
        "--input",
        str(schema_path),
        "--output",
        str(out_path),
    ]
    subprocess.run(cmd, check=True, cwd=BACKEND_ROOT)


def main() -> None:
    if not BUNDLED_SCHEMAS.is_dir():
        sys.exit(f"missing bundled schemas: {BUNDLED_SCHEMAS}")

    rel_src, out_path, src_label, root_name = SCHEMA_JOB

    with tempfile.TemporaryDirectory() as tmp:
        tmp_root = Path(tmp)
        _materialize_stripped_schemas(tmp_root)
        src = tmp_root / rel_src
        if not src.is_file():
            sys.exit(f"missing schema after mirror: {src}")

        out_path.parent.mkdir(parents=True, exist_ok=True)
        _run_codegen(src, out_path)

        text = out_path.read_text(encoding="utf-8")
        text = _rename_root_model(text, root_name)
        text = _replace_generated_header(text, src_label)
        text = _repair_codegen_vc_type_fields(text)
        out_path.write_text(text, encoding="utf-8")

    print("Wrote:", out_path)


if __name__ == "__main__":
    main()
